const appointmentEnums = {
  GET_APPOINTMENT: "GET_APPOINTMENT",
  GET_APPOINTMENT_SUCCESS: "GET_APPOINTMENT_SUCCESS",
  GET_APPOINTMENT_ERROR: "GET_APPOINTMENT_ERROR",
  CREATE_APPOINTMENT: "CREATE_APPOINTMENT",
  CREATE_APPOINTMENT_SUCCESS: "CREATE_APPOINTMENT_SUCCESS",
  CREATE_APPOINTMENT_ERROR: "CREATE_APPOINTMENT_ERROR",
  EDIT_APPOINTMENT: "EDIT_APPOINTMENT",
  EDIT_APPOINTMENT_SUCCESS: "EDIT_APPOINTMENT_SUCCESS",
  EDIT_APPOINTMENT_ERROR: "EDIT_APPOINTMENT_ERROR",
  DELETE_APPOINTMENT: "DELETE_APPOINTMENT",
  DELETE_APPOINTMENT_SUCCESS: "DELETE_APPOINTMENT_SUCCESS",
  DELETE_APPOINTMENT_ERROR: "DELETE_APPOINTMENT_ERROR",
};
export default appointmentEnums;
